# frozen_string_literal: true

# -*- ruby -*-
require 'rake/testtask'
require 'rubocop/rake_task'
require_relative 'lib/pmdtester'

gem 'hoe'
require 'hoe'

Hoe.plugin :bundler
Hoe.plugin :git

hoe = Hoe.spec 'pmdtester' do
  self.version = PmdTester::VERSION

  developer 'Andreas Dangel', 'andreas.dangel@pmd-code.org'
  developer 'Binguo Bao', 'djydewang@gmail.com'
  developer 'Clément Fournier', 'clement.fournier76@gmail.com'

  self.clean_globs = %w[target/reports/**/* target/test/**/* target/dynamic-config.xml Gemfile.lock]
  self.extra_deps += [['nokogiri', '>= 1.11.0.rc4'], ['slop', '~> 4.6'], ['differ', '~> 0.1'],
                      ['rufus-scheduler', '~> 3.5'], ['logger-colors', '~> 1.0'],
                      ['liquid', '>= 4.0']]
  self.extra_dev_deps += [
    ['hoe-bundler',   '~> 1.5'],
    ['hoe-git',       '~> 1.6'],
    ['minitest',      '~> 5.10'],
    ['mocha',         '~> 1.5'],
    # use the same version of rubocop as codacy
    ['rubocop',       '~> 0.81'],
    ['test-unit',     '~> 3.2'],
    ['rdoc',          ['>= 4.0', '< 7']]
  ]
  spec_extras[:required_ruby_version] = '>= 2.7'

  license 'BSD-2-Clause'
end

# Refers to
# http://rubocop.readthedocs.io/en/latest/integration_with_other_tools/#rake-integration
RuboCop::RakeTask.new(:rubocop)

# Run integration test cases
Rake::TestTask.new('integration-test') do |task|
  task.description = 'Run integration test cases'
  task.libs = ['test']
  task.pattern = 'test/**/integration_test_*.rb'
  task.verbose = true
end

desc 'generate the pmdtester.gemspec file'
task 'hoe:spec' do
  attention_message = '# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake hoe:spec`.'
  File.open("#{hoe.name}.gemspec", 'w') do |f|
    f.puts attention_message
    f.puts
    f.write hoe.spec.to_ruby
    f.puts
    f.puts attention_message
  end
end

desc 'verify code quality before committing changes'
task 'verify' => ['clean', 'test', 'rubocop', 'git:manifest', 'hoe:spec', 'check_manifest'] do
  Rake.application.invoke_task('bundler:gemfile[,true]')
end
# vim: syntax=ruby
