# frozen_string_literal: true

# -*- ruby -*-
require 'rake/testtask'
require 'rubocop/rake_task'
require_relative 'lib/pmdtester'

gem 'hoe'
require 'hoe'

Hoe.plugin :bundler
Hoe.plugin :git

hoe = Hoe.spec 'pmdtester' do
  self.version = PmdTester::VERSION

  developer 'Andreas Dangel', 'andreas.dangel@pmd-code.org'
  developer 'Binguo Bao', 'djydewang@gmail.com'
  developer 'Clément Fournier', 'clement.fournier76@gmail.com'

  self.clean_globs = %w[target/reports/**/* target/test/**/* target/dynamic-config.xml]
  self.extra_deps += [
    ['nokogiri',        '~> 1.19'],
    ['slop',            '~> 4.10'],
    ['rufus-scheduler', '~> 3.9'],
    ['logger-colors',   '~> 1.1'],
    ['liquid',          '~> 5.8'],
    ['base64',          '~> 0.3'],
    ['bigdecimal',      '~> 3.2'],
    ['logger',          '~> 1.7']
  ]
  self.extra_dev_deps += [
    ['hoe-bundler',   '~> 1.5'],
    ['hoe-git',       '~> 1.6'],
    ['minitest',      '~> 5.25'],
    ['mocha',         '~> 2.7'],
    ['rubocop',       '~> 1.79'],
    ['test-unit',     '~> 3.7'],
    ['rdoc',          '~> 6.12'],
    ['rake',          '~> 13.3'],
    ['hoe',           '~> 4.2'],
    ['debug',         '~> 1.11']
  ]
  spec_extras[:required_ruby_version] = '>= 3.3'

  license 'BSD-2-Clause'
end

# Refers to
# https://docs.rubocop.org/rubocop/1.60/integration_with_other_tools.html#rake-integration
RuboCop::RakeTask.new(:rubocop)

# Run integration test cases
Rake::TestTask.new('integration-test') do |task|
  task.description = 'Run integration test cases'
  task.libs = ['test']
  task.pattern = 'test/**/integration_test_*.rb'
  task.verbose = true
end

desc 'generate the pmdtester.gemspec file'
task 'hoe:spec' do
  attention_message = '# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake hoe:spec`.'
  File.open("#{hoe.name}.gemspec", 'w') do |f|
    f.puts attention_message
    f.puts
    f.write hoe.spec.to_ruby
    f.puts
    f.puts attention_message
  end
end

desc 'verify code quality before committing changes'
task 'verify' => ['clean', 'test', 'rubocop', 'git:manifest', 'hoe:spec', 'check_manifest'] do
  Rake.application.invoke_task('bundler:gemfile[,true]')
end
# vim: syntax=ruby
