name: manual-integration-tests

on:
  schedule:
    # build it monthly: At 08:30 on day-of-month 1.
    - cron:  '30 8 1 * *'
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  LANG: 'en_US.UTF-8'

jobs:
  build:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 #v5.3.0
        with:
          distribution: 'temurin'
          java-version: |
            11
            21
      - name: Prepare HOME/openjdk11
        run: ln -sfn "${JAVA_HOME_11_X64}" "${HOME}/openjdk11"
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae #v5.0.5
        with:
          path: |
            ~/.m2/repository
            ~/.cache
            ~/.gradle
            vendor/bundle
            target/repositories
          key: v4-${{ runner.os }}-${{ hashFiles('pmdtester.gemspec') }}
          restore-keys: |
            v4-${{ runner.os }}-
      - name: Set up Ruby 4
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af #v1.313.0
        with:
          ruby-version: 4
      - name: Install dependencies (bundler)
        run: |
          # bundler should already be installed
          bundle --version
          bundle config set --local path vendor/bundle
          bundle install
      - name: Run Manual Integration Tests
        run: |
          bundle exec ruby -I test test/manual_integration_tests.rb
